name: Deploy workspace

on:
  workflow_call:
    inputs:
      workspace-name:
        required: true
        type: string
      environment:
        required: true
        type: string
        default: prod

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout monorepo
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          fetch-depth: 2

      - name: Build workspace
        uses: "pagopa/io-platform-migration-toolkit/build-workspace@main"
        with:
          workspace-name: ${{ inputs.workspace-name }}

      - name: Make workspace artifact
        id: make_artifact
        uses: "pagopa/io-platform-migration-toolkit/make-workspace-artifact@main"
        with:
          workspace-name: ${{ inputs.workspace-name }}

      - name: Upload workspace artifact
        uses: actions/upload-artifact@694cdabd8bdb0f10b2cea11669e1bf5453eed0a6 # v4.2.0
        with:
          name: ${{ inputs.workspace-name }}
          path: ${{ steps.make_artifact.outputs.artifact-path }}

  deploy:
    name: Deploy
    if: ${{ !github.event.act }}
    needs: [build]
    runs-on: self-hosted
    environment: ${{ inputs.environment }}

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download workspace artifact
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: ${{ inputs.workspace-name }}

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to ${{ vars.AZURE_WEB_APP_NAME }} staging slot
        uses: azure/webapps-deploy@v2
        with:
          resource-group-name: ${{ vars.AZURE_WEB_APP_RESOURCE_GROUP }}
          app-name: ${{ vars.AZURE_WEB_APP_NAME }}
          slot-name: staging
          package: ${{ inputs.workspace-name }}.zip

      - name: Check staging health
        run: curl --retry 5 --retry-max-time 120 --retry-all-errors -f 'https://${{ vars.AZURE_WEB_APP_NAME }}-staging.azurewebsites.net${{ vars.HEALTH_CHECK_PATH }}'

      - name: Swap staging slot with production
        run: az webapp deployment slot swap -g ${{ vars.AZURE_WEB_APP_RESOURCE_GROUP }} -n ${{ vars.AZURE_WEB_APP_NAME }} --slot staging --target-slot production
