name: PNPM Job

on:
  workflow_call:
    inputs:
      command:
        description: pnpm script to run
        required: true
        type: string
      fail_on_git_diff:
        description: Fail if the command changes tracked files
        required: false
        type: boolean
        default: false

jobs:
  run:
    name: ${{ inputs.command }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Run pnpm ${{ inputs.command }}
        run: pnpm ${{ inputs.command }}

      - name: Fail if git diff is not empty
        if: ${{ inputs.fail_on_git_diff }}
        run: git diff --exit-code
