name: PNPM Job

on:
  workflow_call:
    inputs:
      command:
        description: pnpm script to run
        required: true
        type: string
      fail_on_git_diff:
        description: Fail if the command changes tracked files
        required: false
        type: boolean
        default: false

jobs:
  run:
    name: ${{ inputs.command }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4
        with:
          # Avoid double install; we run pnpm install after cache setup.
          run_install: false

      - name: Setup node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version-file: package.json
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run pnpm ${{ inputs.command }}
        run: pnpm ${{ inputs.command }}

      - name: Fail if git diff is not empty
        if: ${{ inputs.fail_on_git_diff }}
        run: git diff --exit-code
